name: accent-classifier
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - librosa
  - matplotlib
  - joblib
  - streamlit
  - pip
  - pip:
      - soundfile
